<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
        <PackageReference Include="Telegram.BotAPI" Version="9.2.0"/>
        <PackageReference Include="Telegram.BotAPI.Extensions" Version="0.6.2"/>
    </ItemGroup>

</Project>
